version: '2'

services:
  coachme-ui:
    image: ${DOCKER_REGISTRY}/${UI_IMAGE}:${UI_TAG}
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coachmeweb.rule=Host(`coachme.roncarter.co.uk`)"
      - "traefik.http.routers.coachmeweb.entrypoints=web"      
      
networks:
  merit:
  edge:
    external:
      name: edge
