version: '3.1'

services:
  ui:
    image: #{DOCKER_REGISTRY}/#{Octopus.Action.Package[CoachMeWeb].PackageId}:#{Octopus.Action.Package[CoachMeWeb].PackageVersion}
    environment:
      - DOTNET_ENVIRONMENT=#{ENVIRONMENT}
      - VUE_APP_API=#{API}
    networks:
      - edge
    deploy:
      placement:
          constraints:
            - "node.role==worker"
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.coachme-ui.loadbalancer.server.port=80"
        - "traefik.http.middlewares.#{SubDomain}-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.#{SubDomain}-http.entrypoints=web"
        - "traefik.http.routers.#{SubDomain}-http.middlewares=#{SubDomain}-https-redirect@docker"
        - "traefik.http.routers.#{SubDomain}-http.rule=Host(`#{HostUrl}`)"
        - "traefik.http.routers.#{SubDomain}-https.entrypoints=websecure"
        - "traefik.http.routers.#{SubDomain}-https.rule=Host(`#{HostUrl}`)"
        - "traefik.http.routers.#{SubDomain}-https.tls.certresolver=myresolver" 
      
networks:
  edge:
    external:
      name: edge
