version: '2'

services:
  coachme-ui:
    image: ${DOCKER_REGISTRY}/${UI_IMAGE}:${UI_TAG}
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
    networks:
      - edge
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.http.middlewares.coachme-web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.coachme-web-http.entrypoints=web"
      - "traefik.http.routers.coachme-web-http.middlewares=coachme-web-https-redirect@docker"
      - "traefik.http.routers.coachme-web-http.rule=Host(`coachme.roncarter.co.uk`)"
      - "traefik.http.routers.coachme-web-https.entrypoints=websecure"
      - "traefik.http.routers.coachme-web-https.rule=Host(`coachme.roncarter.co.uk`)"
      - "traefik.http.routers.coachme-web-https.tls.certresolver=myresolver" 
      
networks:
  edge:
    external:
      name: edge
